### ISSUE TITLE
Cannot allocate memory - 48GB Ram

### ISSUE THREAD

**Issue by StanGirard** [zugzwang/batchgcd#12]
Reading product tree level from data/product_tree/level25.gmp
   ok, read 1 ints of 40158364888 bits
   Computing partial remainders 0 of 24
GNU MP: Cannot allocate memory (size=4563664912)
Aborted (core dumped)

**Comment by zugzwang** [comment]
Hello,
This is probably due to insufficient RAM. With a 25-level tree, you're working with around 30M moduli and you need more RAM.

How many threads are you using? Because in your case each level weighs around 5GB. Single threading, there are at most 2 tree levels in RAM simultaneously so it looks like a memory optimization can be made here (although more RAM would do the trick for now).

**Comment by StanGirard** [comment]
Hey, thanks for the answer. Yeah I understood where the error came from. I'm working with 5.019 Go numbers. I have 11 cores assigned, so it tries to allocate 55GB in RAM. I'm looking right now for an optimisation of  :
```C++
for(unsigned int i = 0; i < _new->size(); i += N_THREADS) {
        vector<boost::thread> threads;
        for(int j = 0; j < N_THREADS; j++) {
```

Where ```i += min(2**levels-2-l, N_THREADS) ```

**Comment by zugzwang** [comment]
Hi, I didn't see your comment in time. But there was a memory leak here, actually, because it is wrong to allocate memory for 11 threads if we're actually using one.
I made the following modification in both multithreading functions:
```
    int n_threads = min(N_THREADS, <necessary threads>);
```
And now it only allocates threads it needs. I'll post the PR (this was actually mentioned in #6 )

**Comment by StanGirard** [comment]
Cool ! Looking forward to it.

**Comment by zugzwang** [comment]
So now when you're computing partial 1 remainder of a 5BG integer, it won't be copied 11 times. It knows it needs only one thread for that. Please let me know if it is better now.

**Comment by StanGirard** [comment]
I'll try ! Thanks

**Comment by StanGirard** [comment]
```
Reading product tree level from data/product_tree/level25.gmp
   ok, read 1 ints of 40158364888 bits
   Computing partial remainders 0 of 24
GNU MP: Cannot allocate memory (size=4563664912)
Aborted (core dumped)
```

Same error

**Comment by zugzwang** [comment]
Hello, I just confirmed with `gdb` that it's using two threads when it failed (also, see latest update to `master`, it now displays how many threads were used).
So this is not related to the 11 threads, but rather unnecessary variable allocation. I'm currently working on this in a separate branch.

**Comment by zugzwang** [comment]
See #13 , although I do not know for sure that less memory is allocated.
At this point (part B of the algorithm,iteration 0), you should have ~15GB of used RAM:

- Nothing from `main` or `product_tree`  (`input_moduli` is freed in `product_tree`)
- `remainders_square_fast`: `R` and `newR`, which are new. In this iteration, `R` is the product (5GB in your case) and `newR` is empty.
- `multithread_partial_remainders, i = 0`: `_R` is `R`, `_new` is `newR` so no memory. Then for each thread (2 threads are in use here), `value` is defined and gets squared. Since it's one level down, `value` is 5GB after squared and gets appended to `_new`.
That makes a total of `|R| + threads * |value|` memory in this part of the algorithm, i.e., `5 + 2 * 5 = 15GB`.

Does this make sense? Let me know if it still feels like memory is getting doubled somewhere.

EDIT:

Just tried 2M keys and the results are no better than before. Looks like a multithreading issue, or less probably, internals of `mpz`'s `C++` wrapper.

**Comment by StanGirard** [comment]
I just tried with the same parameters. The memory keeps going higher and higher.
It start at 15GB and goes up and up to almost all of it.
<img width="762" alt="Capture d’écran 2019-12-13 à 11 02 55" src="https://user-images.githubusercontent.com/19614572/70791957-7bf35300-1d98-11ea-8c4f-e530c16b2c93.png">
<img width="762" alt="Capture d’écran 2019-12-13 à 11 02 42" src="https://user-images.githubusercontent.com/19614572/70791958-7bf35300-1d98-11ea-9158-8d88e781c90a.png">

<img width="762" alt="Capture d’écran 2019-12-13 à 11 03 48" src="https://user-images.githubusercontent.com/19614572/70791955-7bf35300-1d98-11ea-8c03-5e0cd31efc7a.png">

You can see the time difference with the uptime value. 

I'll look into the code deeper.

**Comment by StanGirard** [comment]
Could there be a fragmenting issue with multithreading ?

**Comment by StanGirard** [comment]
Maybe we could look into a custom malloc, realloc, calloc, free ? 
[GMPLIB-Custom Allocation](https://gmplib.org/manual/Custom-Allocation.html)

**Comment by zugzwang** [comment]
Hello Stan! Sorry for the delay. 
If it starts at 15GB, it's definitely `std::vector` allocating more than it should, not GMP. (For the first part of the algorithm, 5GB should be allocated). I'm looking at this today and will at least confirm this, but I may be off until Thursday.

**Comment by StanGirard** [comment]
No worries, got plenty on my plate this week too.

**Comment by zugzwang** [comment]
Hello Stan!
Normally, this is related to the fact that `std::vector`s are contiguous in memory (so that every `push_back` needs some memory and move things around to avoid fragmenting, so I confirm the issue.

Honestly I don't see a clear fix here, other than trying with `std::list` or `std::deque`.

In any case, and maybe, the `~3` factor in memory is already reasonable for this functionality. Needing 100Gb of memory to compute gcds of 30M of 2048bit integers looks reasonable.

**Comment by Bonbonb12** [comment]
https://github.com/zugzwang/batchgcd/issues/6#issue-530744661
